package EulerProblems;

import java.util.Scanner;

/**
 * Created by cvalencia on 6/1/16.
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem2 {

    public static void main(String args[]) {
        System.out.println("Max Fibonacci term?");
        Scanner s = new Scanner(System.in);
        int max = s.nextInt();
        int i1 = 1;
        int i2 = 1;
        int total = 0;
        int temp;
        while (i1 + i2 < max){
            temp = i2 + i1;
            i1 = i2;
            i2 = temp;
            if (i2%2 == 0){
                //System.out.println(i2);
                total += i2;
            }
        }
        System.out.println("Total sum of even-valued terms below " + max +": " + total);
    }
}
